[package]
name = "FinSc-Cosmos-Wiki"
version = "0.3.0"
ipkg = "FinSc-Cosmos-Wiki.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Multiset-Binary]
type = "local"
path = "../FinSc-Multiset-Binary"
ipkg = "FinSc-Multiset-Binary.ipkg"

[custom.all.FinSc-Multiset-Ternary]
type = "local"
path = "../FinSc-Multiset-Ternary"
ipkg = "FinSc-Multiset-Ternary.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Physics]
type = "local"
path = "../FinSc-Physics"
ipkg = "FinSc-Physics.ipkg"

[custom.all.FinSc-Hadron]
type = "local"
path = "../FinSc-Hadron"
ipkg = "FinSc-Hadron.ipkg"

[custom.all.FinSc-Chemistry]
type = "local"
path = "../FinSc-Chemistry"
ipkg = "FinSc-Chemistry.ipkg"

[custom.all.FinSc-Biology]
type = "local"
path = "../FinSc-Biology"
ipkg = "FinSc-Biology.ipkg"

[custom.all.FinSc-Cosmos]
type = "local"
path = "../FinSc-Cosmos"
ipkg = "FinSc-Cosmos.ipkg"
