[custom.all.idris2-Universe-Wiki]
type = "local"
path = "."
ipkg = "idris2-Universe-Wiki.ipkg"

[custom.all.idris2-LUniverse]
type = "local"
path = "../idris2-Universe"
ipkg = "idris2-LUniverse.ipkg"

[custom.all.idris2-chromogeometry]
type = "local"
path = "../idris2-Chromogeometry"
ipkg = "idris2-chromogeometry.ipkg"

[custom.all.idris2-Multiset]
type = "local"
path = "../idris2-Multiset"
ipkg = "idris2-Multiset.ipkg"

[custom.all.idris2-ref1]
type = "local"
path = "../Library/Src/idris2-ref1"
ipkg = "ref1.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
